"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { handleFieldValidationOnInput, handleInvalidSubmit } from "@/lib/form-validation";
export function ContactForm({ sourcePage, leadType = "kontakt" }) {
    const handleSubmit = (event) => {
        handleInvalidSubmit(event);
    };
    const handleFieldInput = (event) => {
        handleFieldValidationOnInput(event);
    };
    return (_jsxs("form", { className: "form", noValidate: true, onSubmit: handleSubmit, onInput: handleFieldInput, children: [_jsx("input", { type: "hidden", name: "lead_type", value: leadType }), _jsx("input", { type: "hidden", name: "source_page", value: sourcePage }), _jsx("input", { type: "hidden", name: "language", value: "pl" }), _jsx("input", { type: "hidden", name: "utm_source", value: "" }), _jsx("input", { type: "hidden", name: "utm_medium", value: "" }), _jsx("input", { type: "hidden", name: "utm_campaign", value: "" }), _jsxs("label", { children: ["Imi\u0119 i nazwisko ", _jsx("span", { className: "required-mark", children: "*" }), _jsx("input", { type: "text", name: "full_name", placeholder: "Jan Kowalski", required: true })] }), _jsxs("label", { children: ["Telefon ", _jsx("span", { className: "required-mark", children: "*" }), _jsx("input", { type: "tel", name: "phone", placeholder: "+48 000 000 000", required: true })] }), _jsxs("label", { children: ["E-mail", _jsx("input", { type: "email", name: "email", placeholder: "jan@email.com" })] }), _jsxs("label", { children: ["Miasto / dzielnica", _jsx("input", { type: "text", name: "city_or_district", placeholder: "Warszawa, Mokot\u00F3w" })] }), _jsxs("label", { children: ["Preferowana godzina kontaktu", _jsx("input", { type: "text", name: "preferred_contact_time", placeholder: "Np. 10:00-12:00" })] }), _jsxs("label", { children: ["Kr\u00F3tki opis zapytania", _jsx("textarea", { name: "message", rows: 4, placeholder: "Napisz, czego potrzebujesz i jakiej nieruchomosci dotyczy temat." })] }), _jsxs("label", { className: "form-consent", children: [_jsx("input", { className: "consent-checkbox", type: "checkbox", name: "consent_data", required: true }), " Wyrazam zgode na przetwarzanie danych kontaktowych ", _jsx("span", { className: "required-mark", children: "*" })] }), _jsxs("button", { type: "submit", children: [_jsxs("span", { className: "prefooter-btn-text-wrap", "aria-hidden": "true", children: [_jsx("span", { className: "prefooter-btn-text prefooter-btn-text-top", children: "Wy\u015Blij zapytanie" }), _jsx("span", { className: "prefooter-btn-text prefooter-btn-text-bottom", children: "Wy\u015Blij zapytanie" })] }), _jsx("span", { className: "sr-only", children: "Wy\u015Blij zapytanie" }), _jsx("span", { className: "prefooter-btn-arrow", "aria-hidden": "true", children: "\u2192" })] })] }));
}
