"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { usePathname } from "next/navigation";
import { ROUTE_PATHS, getFooterLinks } from "@/config/navigation";
export function SiteFooter({ year }) {
    const pathname = usePathname();
    const visibleFooterLinks = getFooterLinks(pathname);
    return (_jsxs("footer", { className: "site-footer", children: [_jsxs("div", { className: "container footer-shell", children: [_jsxs("div", { className: "footer-brand", children: [_jsx("a", { href: ROUTE_PATHS.home, className: "footer-logo", "aria-label": "FIND home", children: _jsx("img", { src: "/LOGO.png", alt: "FIND" }) }), _jsx("p", { className: "footer-copy", children: "Eksperckie wsparcie w\u0142a\u015Bciciela mieszkania: od strategii ceny po bezpieczny podpis." })] }), _jsx("div", { className: "footer-links", children: visibleFooterLinks.map((link) => (_jsx("a", { href: link.href, children: link.label }, link.href))) }), _jsxs("div", { className: "footer-social", children: [_jsxs("a", { href: "#", "aria-label": "Instagram", children: [_jsx("span", { className: "social-ico", "aria-hidden": "true", children: _jsxs("svg", { viewBox: "0 0 24 24", fill: "none", children: [_jsx("rect", { x: "3.5", y: "3.5", width: "17", height: "17", rx: "5" }), _jsx("circle", { cx: "12", cy: "12", r: "4.1" }), _jsx("circle", { cx: "17.35", cy: "6.65", r: "1" })] }) }), "Instagram"] }), _jsxs("a", { href: "#", "aria-label": "Facebook", children: [_jsx("span", { className: "social-ico", "aria-hidden": "true", children: _jsx("svg", { viewBox: "0 0 24 24", fill: "none", children: _jsx("path", { d: "M14.2 8.1h2.2V4.5h-2.6c-3 0-4.6 1.8-4.6 4.9v2H6.8v3.7h2.4V20h3.8v-4.9h2.9l.5-3.7h-3.4V9.8c0-1 .4-1.7 1.6-1.7Z" }) }) }), "Facebook"] }), _jsxs("a", { href: "#", "aria-label": "LinkedIn", children: [_jsx("span", { className: "social-ico", "aria-hidden": "true", children: _jsxs("svg", { viewBox: "0 0 24 24", fill: "none", children: [_jsx("rect", { x: "4", y: "9.2", width: "3.4", height: "10.8" }), _jsx("circle", { cx: "5.7", cy: "5.8", r: "1.6" }), _jsx("path", { d: "M10 9.2h3.3v1.5c.6-1 1.8-1.8 3.6-1.8 3 0 4.1 2 4.1 5.1V20h-3.5v-5.3c0-1.7-.6-2.6-1.9-2.6-1.5 0-2.2 1.1-2.2 2.6V20H10V9.2Z" })] }) }), "LinkedIn"] })] })] }), _jsx("div", { className: "container footer-bottom", children: _jsxs("p", { children: ["\u00A9 ", year, " FIND. Wszelkie prawa zastrze\u017Cone."] }) })] }));
}
